# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 24.9.2
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2024.12.31-h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.40-h12ee557_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2025a-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h5eee18b_6.conda
https://repo.anaconda.com/pkgs/main/linux-64/expat-2.6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libiconv-1.16-h5eee18b_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/oniguruma-6.9.7.1-h27cfd23_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.15-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.6.4-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46306.conda
https://repo.anaconda.com/pkgs/main/linux-64/jq-1.7.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pcre2-10.42-hebb0a14_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.14-h39e8969_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libglib-2.78.4-hdc74915_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h213fc3f_46344.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.45.3-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-tools-2.78.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.11.11-he870216_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/attrs-24.3.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/brotli-python-1.0.9-py311h6a678d5_9.conda
https://repo.anaconda.com/pkgs/main/linux-64/certifi-2025.1.31-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-3.3.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/crashtest-0.4.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/distlib-0.3.8-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/filelock-3.13.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/glib-2.78.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/idna-3.7-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jeepney-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/lockfile-0.12.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-service-2.4.0-py311h5eee18b_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/more-itertools-10.3.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/msgpack-python-1.0.3-py311hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-24.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pkginfo-1.11.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/platformdirs-2.5.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/poetry-core-1.5.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyproject_hooks-1.0.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.7.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-installer-0.6.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-6.0.2-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/rpds-py-0.22.3-py311h4aa5aa6_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-72.1.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/shellingham-1.5.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tomlkit-0.13.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/trove-classifiers-2024.10.14-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/webencodings-0.5.1-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.45.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xmltodict-0.14.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zipp-3.21.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.17.1-py311h1fdaa30_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/dbus-1.13.18-hb2f20db_0.conda
https://repo.anaconda.com/pkgs/main/noarch/html5lib-1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/importlib-metadata-8.5.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jaraco.classes-3.2.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-base-2.2.2-py311hf175353_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-25.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/poetry-plugin-export-1.3.0-py311h4849bfd_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-build-0.10.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/referencing-0.30.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/virtualenv-20.17.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-43.0.3-py311h7825ff9_1.conda
https://repo.anaconda.com/pkgs/main/noarch/importlib_metadata-8.5.0-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-specifications-2023.7.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/argcomplete-1.12.0-py_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jsonschema-4.23.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-24.2.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/secretstorage-3.3.1-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/keyring-23.13.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.26.19-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/yq-2.12.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/dulwich-0.21.3-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.32.3-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/cachecontrol-0.12.11-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/noarch/requests-toolbelt-0.9.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/cleo-2.1.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/poetry-1.4.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_fft-1.3.11-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl_random-1.2.8-py311ha02d727_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/numpy-2.2.2-py311h08b1b3b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/rapidfuzz-3.12.1-py311h6a678d5_0.conda
