dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: arch
    box: archlinux/archlinux
    memory: 1024
    cpus: 1
    interfaces:
      - network_name: private_network
        ip: 192.168.56.101

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: testinfra
  directory: tests
  options:
    sudo: true

scenario:
  test_sequence:
    - create
    - converge
    - idempotence
    - verify
    - destroy
